---
kind: pipeline
type: kubernetes
name: testing

platform:
  os: linux
  arch: amd64

steps:
- name: vet
  pull: always
  image: golang:1.11
  commands:
  - go vet ./...
  environment:
    GO111MODULE: on
  volumes:
  - name: gopath
    path: /go

- name: test
  pull: always
  image: golang:1.11
  commands:
  - go test -cover ./...
  environment:
    GO111MODULE: on
  volumes:
  - name: gopath
    path: /go

volumes:
  - name: gopath
    host:
      path: /es-data/go/${DRONE_REPO}/${DRONE_BRANCH}

node_selector:
  kubernetes.io/hostname: efk

---
kind: pipeline
type: kubernetes
name: linux-amd64-docker

platform:
  os: linux
  arch: amd64

steps:
- name: build-push
  pull: always
  image: golang:1.11
  commands:
  - "go build -v -ldflags \"-X main.version=${DRONE_COMMIT_SHA:0:8}\" -a -tags netgo -o release/linux/amd64/drone-docker ./cmd/drone-docker"
  environment:
    CGO_ENABLED: 0
    GO111MODULE: on

- name: executable
  pull: always
  image: golang:1.11
  commands:
  - ./release/linux/amd64/drone-docker --help


- name: publish
  pull: always
  image: plugins/docker:18
  settings:
    auto_tag: true
    auto_tag_suffix: develop
    daemon_off: false
    dockerfile: docker/docker/Dockerfile.linux.amd64
    repo: registry.cloudclusters.net/cloudclusters/plugins-docker
    registry: registry.cloudclusters.net
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  volumes:
    - name: dockercache
      path: /var/lib/docker



depends_on:
- testing

node_selector:
  kubernetes.io/hostname: efk

volumes:
  - name: dockercache
    host:
      path: /es-data/docker/${DRONE_REPO}/${DRONE_BRANCH}


